/** Mapeia caminho ou extensão para identificador suportado pelo refractor/prism (react-syntax-highlighter). */
const EXT_TO_LANG: Record<string, string> = {
  ts: "typescript",
  tsx: "tsx",
  mts: "typescript",
  cts: "typescript",
  js: "javascript",
  jsx: "jsx",
  mjs: "javascript",
  cjs: "javascript",
  json: "json",
  jsonc: "json",
  json5: "json5",
  css: "css",
  scss: "scss",
  sass: "sass",
  less: "less",
  html: "markup",
  htm: "markup",
  xml: "markup",
  cshtml: "markup",
  md: "markdown",
  mdx: "markdown",
  sql: "sql",
  py: "python",
  rb: "ruby",
  java: "java",
  kt: "kotlin",
  kts: "kotlin",
  cs: "csharp",
  fs: "fsharp",
  go: "go",
  rs: "rust",
  swift: "swift",
  php: "php",
  vue: "markup",
  svelte: "markup",
  yaml: "yaml",
  yml: "yaml",
  sh: "bash",
  bash: "bash",
  zsh: "bash",
  ps1: "powershell",
  dockerfile: "docker",
  gradle: "groovy",
  groovy: "groovy",
  properties: "properties",
  toml: "toml",
  ini: "ini",
  plist: "markup",
  xaml: "markup",
  cpp: "cpp",
  cc: "cpp",
  cxx: "cpp",
  h: "cpp",
  hpp: "cpp",
  c: "c",
  hcl: "hcl",
  tf: "hcl",
  graphql: "graphql",
  proto: "protobuf",
  r: "r",
  dart: "dart",
  lua: "lua",
  pl: "perl",
  pm: "perl",
  clj: "clojure",
  cljs: "clojure",
  ex: "elixir",
  exs: "elixir",
  erl: "erlang",
  scala: "scala",
  sol: "solidity",
  wasm: "wasm",
  vim: "vim",
  bat: "batch",
  cmd: "batch",
};

const MARKDOWN_LANG_ALIASES: Record<string, string> = {
  ts: "typescript",
  typescript: "typescript",
  js: "javascript",
  javascript: "javascript",
  py: "python",
  sh: "bash",
  shell: "bash",
  zsh: "bash",
  yml: "yaml",
  md: "markdown",
  html: "markup",
  xml: "markup",
  text: "clike",
  txt: "clike",
  plaintext: "clike",
};

const SAFE_LANGS = new Set([
  "typescript",
  "tsx",
  "javascript",
  "jsx",
  "json",
  "json5",
  "css",
  "scss",
  "sass",
  "less",
  "markup",
  "markdown",
  "sql",
  "python",
  "ruby",
  "java",
  "kotlin",
  "csharp",
  "fsharp",
  "go",
  "rust",
  "swift",
  "php",
  "yaml",
  "bash",
  "powershell",
  "docker",
  "groovy",
  "properties",
  "toml",
  "ini",
  "cpp",
  "c",
  "hcl",
  "graphql",
  "protobuf",
  "r",
  "dart",
  "lua",
  "perl",
  "clojure",
  "elixir",
  "erlang",
  "scala",
  "solidity",
  "wasm",
  "vim",
  "batch",
  "clike",
]);

function normalizeLang(id: string): string {
  const lower = id.trim().toLowerCase();
  return MARKDOWN_LANG_ALIASES[lower] ?? lower;
}

export function pathToPrismLanguage(filePath: string): string {
  const base = filePath.split(/[/\\]/).pop() ?? filePath;
  const dot = base.lastIndexOf(".");
  const ext = dot >= 0 ? base.slice(dot + 1).toLowerCase() : "";
  const fromExt = ext ? EXT_TO_LANG[ext] : "";
  const candidate = normalizeLang(fromExt || ext || "clike");
  return SAFE_LANGS.has(candidate) ? candidate : "clike";
}

/** Normaliza rótulo vindo de ```ts / ```javascript no Markdown. */
export function fenceLangToPrism(lang: string | undefined): string {
  if (!lang?.trim()) return "clike";
  const candidate = normalizeLang(lang.trim());
  return SAFE_LANGS.has(candidate) ? candidate : "clike";
}
